
package com.microfocus.silkcentral.webservices.tests.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "WSFaultException", targetNamespace = "http://www.microfocus.com/silkcentral/webservices/tests")
public class WSFaultException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private WsFaultBean faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public WSFaultException(String message, WsFaultBean faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public WSFaultException(String message, WsFaultBean faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.microfocus.silkcentral.webservices.tests.stubs.WsFaultBean
     */
    public WsFaultBean getFaultInfo() {
        return faultInfo;
    }

}
